src/NetCoreBBS/Areas/Admin/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using NetCoreBBS.Infrastructure;
using NetCoreBBS.Entities;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace NetCoreBBS.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize("Admin")]
    public class TopicController : Controller
    {
        private DataContext _context;
        public TopicController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var pagesize = 20;
            var pageindex = 1;
            if (!string.IsNullOrEmpty(Request.Query["page"]))
                pageindex = Convert.ToInt32(Request.Query["page"]);
            var topics = _context.Topics.AsQueryable();
            var count = topics.Count();
            var topiclist = topics
                .OrderByDescending(r => r.CreateOn)
                .OrderByDescending(r => r.Top)                
                .Skip(pagesize * (pageindex - 1))
                .Take(pagesize).ToList();
            ViewBag.PageIndex = pageindex;
            ViewBag.PageCount = count % pagesize == 0 ? count / pagesize : count / pagesize + 1;
            return View(topiclist);
        }

        public IActionResult Delete(int id)
        {
            var topic = _context.Topics.FirstOrDefault(r => r.Id == id);
            if (topic != null)
            {
                _context.Topics.Remove(topic);
                var replys=_context.TopicReplys.Where(r => r.TopicId == id).ToList();
                _context.TopicReplys.RemoveRange(replys);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return Content("出现异常");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSave(Topic topic)
        {
            _context.Attach(topic);
            _context.Entry(topic).Property(r => r.Title).IsModified = true;
            _context.Entry(topic).Property(r => r.Content).IsModified = true;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id, string type)
        {
            var topic = _context.Topics.FirstOrDefault(r => r.Id == id);
            if (topic != null)
            {
                switch (type)
                {
                    case "top":
                        topic.Top = 1;
                        break;
                    //case "good":
                    //    topic.Good = true;
                    //    break;
                    case "notop":
                        topic.Top = 0;
                        break;
                    //case "nogood":
                    //    topic.Good = false;
                    //    break;
                }
                _context.Update(topic);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return Content("出现异常");
        }
    }
}

src/NetCoreBBS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetCoreBBS.Interfaces;
using NetCoreBBS.Entities;
using Microsoft.AspNetCore.Authorization;
using NetCoreBBS.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace NetCoreBBS.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private ITopicRepository _topic;
        private ITopicReplyRepository _reply;
        private UserManager<User> UserManager;
        private IHostingEnvironment _env;
        public UserController(ITopicRepository topic, ITopicReplyRepository reply, UserManager<User> userManager, IHostingEnvironment env)
        {
            _topic = topic;
            _reply = reply;
            UserManager = userManager;
            _env = env;
        }
        public IActionResult Index()
        {
            var u = UserManager.GetUserAsync(User).Result;
            var topics = _topic.List(r => r.UserId == u.Id).ToList();
            var replys = _reply.List(r => r.ReplyUserId == u.Id).ToList();
            ViewBag.Topics = topics;
            ViewBag.Replys = replys;
            return View(u);
        }

        public IActionResult Edit()
        {
            return View(UserManager.GetUserAsync(User).Result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel usermodel)
        {
            var user = UserManager.GetUserAsync(User).Result;
            if (ModelState.IsValid)
            {
                if (usermodel.Avatar != null)
                {
                    var avatar = usermodel.Avatar;
                    if (avatar.Length / 1024 > 100)
                    {
                        return Content("头像文件大小超过100KB");
                    }
                    var ext = Path.GetExtension(avatar.FileName);
                    var avatarpath = Path.Combine("images", "avatar", user.Id + ext);
                    var filepath = Path.Combine(_env.WebRootPath, avatarpath);
                    using (FileStream fs = new FileStream(filepath, FileMode.Create))
                    {
                        avatar.CopyTo(fs);
                        fs.Flush();
                    }
                    user.Avatar = avatarpath;
                }
                user.Email = usermodel.Email;
                user.Url = usermodel.Url;
                user.GitHub = usermodel.GitHub;
                user.Profile = usermodel.Profile;
                await UserManager.UpdateAsync(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }
    }
}

src/NetCoreBBS/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -NetCoreBBS后台管理</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/dashboard.css" rel="stylesheet" />
        <link href="~/lib/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/css/dashboard.css" rel="stylesheet" asp-append-version="true"/>
        <link href="~/lib/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">NetCoreBBS</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">欢迎 admin</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li><a asp-action="Index" asp-controller="Manage" asp-area="Admin">总览</a></li>
                    <li><a asp-action="Index" asp-controller="Topic" asp-area="Admin">主题管理</a></li>
                    <li><a asp-action="Index" asp-controller="User" asp-area="Admin">用户管理</a></li>
                    <li><a asp-action="Index" asp-controller="Node" asp-area="Admin">节点管理</a></li>                    
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-markdown/js/bootstrap-markdown.js"></script>
        <script src="~/js/markdown.js"></script>
        <script src="~/js/to-markdown.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/bootstrap-markdown/js/bootstrap-markdown.js"></script>
        <script src="~/js/markdown.js"></script>
        <script src="~/js/to-markdown.js"></script>
    </environment>
    <script>
        $(".nav-sidebar li a").each(function () {
            var path = location.pathname;
            var href = $(this).attr("href");
            if (href == path)
                $(this).parent().addClass("active");
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/NetCoreBBS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreBBS</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />        
        <link href="~/lib/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/lib/bootstrap-markdown/css/bootstrap-markdown.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand"><b>NetCoreBBS</b></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                @await Html.PartialAsync("_LoginPartial")
                <form class="navbar-form navbar-right" asp-controller="Home" asp-action="Index" method="get">
                    <input type="text" class="form-control" name="s" placeholder="搜索...">
                </form>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p><a href="http://www.cnblogs.com/linezero/" target="_blank">LineZero</a>&copy; 2016 - NetCoreBBS</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-markdown/js/bootstrap-markdown.js"></script>
        <script src="~/js/markdown.js"></script>
        <script src="~/js/to-markdown.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/bootstrap-markdown/js/bootstrap-markdown.js"></script>
        <script src="~/js/markdown.js"></script>
        <script src="~/js/to-markdown.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/NetCoreBBS/Views/Shared/_PagerPartial.cshtml
@{
    var pageindex = Convert.ToInt32(ViewBag.PageIndex);
    var pagecount = Convert.ToInt32(ViewBag.PageCount);
    pagecount = pagecount == 0 ? 1 : pagecount;
    pageindex = pageindex > pagecount ? pagecount : pageindex;
    var path = Context.Request.Path.Value;
    var query = string.Empty;
    var querys = Context.Request.Query;
    foreach (var item in querys)
    {
        if (!item.Key.Equals("page"))
        {
            query += $"{item.Key}={item.Value}&";
        }
    }
    query = query == string.Empty ? "?" : "?" + query;
    path += query;
    var pagestart = pageindex - 2 > 0 ? pageindex - 2 : 1;
    var pageend = pagestart + 5 >= pagecount ? pagecount : pagestart + 5;
}
<ul class="pagination">
    <li class="prev previous_page @(pageindex == 1 ? "disabled" : "")">
        <a href="@(pageindex==1?"#":$"{path}page={pageindex - 1}")">&#8592; 上一页</a>
    </li>
    <li @(pageindex == 1 ? "class=active" : "")><a rel="start" href="@(path)page=1">1</a></li>
    @if (pagestart > 2)
    {
        <li class="disabled"><a href="#">&hellip;</a></li>
    }
    @for (int i = pagestart; i < pageend; i++)
    {
        if (i > 1)
        {
            <li @(pageindex == i ? "class=active" : "")><a rel="next" href="@(path)page=@i">@i</a></li>
        }
    }
    @if (pageend < pagecount)
    {
        <li class="disabled"><a href="#">&hellip;</a></li>
    }
    @if (pagecount > 1)
    {
        <li @(pageindex == pagecount ? "class=active" : "")><a rel="end" href="@(path)page=@pagecount">@pagecount</a></li>
    }
    <li class="next next_page @(pageindex==pagecount?"disabled":"")">
        <a rel="next" href="@(pageindex==pagecount?"#":$"{path}page={pageindex + 1}")">下一页 &#8594;</a>
    </li>
</ul>

src/NetCoreBBS/Views/Shared/_SidebarPartial.cshtml
@using NetCoreBBS.ViewComponents
<div class="panel panel-default" style="margin-top:20px;">
    <div class="panel-heading">
        <h3 class="panel-title">.NET Core 跨平台论坛介绍</h3>
    </div>
    <div class="panel-body">
        .NET Core 开发<br />
        VS Code 或者 VS 2017<br />
        更多详细：<a href="http://dot.net" target="_blank">dot.net</a><br />
        <h3>论坛系统介绍：</h3>
        系统开发：<br />
        ASP.NET Core + EF Core Sqlite + Bootstrap <br />
        运行环境：<br />
        Ubuntu 14.04 + Kestrel <br /><br />
        博客介绍：
        <a href="http://www.cnblogs.com/linezero/" target="_blank">
            LineZero's Blog
        </a><br />
        GitHub：
        <a href="https://github.com/linezero/NETCoreBBS" target="_blank">
            NETCoreBBS
        </a><br />
        服务器时间：@DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")
    </div>
</div>
@(await Component.InvokeAsync<TopicRankList>(new { days = 30 }))
@(await Component.InvokeAsync<Statistics>())